[package]
name = "rust-kanji-rand"
version = "0.1.0"
authors = ["Henke Adolfsson <catears13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
